apiVersion: v1
kind: Secret
metadata:
  name: distributed-sql-object-store
type: Opaque
stringData:
  DISTRIBUTED_SQL_COORDINATOR_OBJECT_STORE_ACCESS_KEY: distributed-sql
  DISTRIBUTED_SQL_COORDINATOR_OBJECT_STORE_SECRET_KEY: distributed-sql-secret
  DISTRIBUTED_SQL_COORDINATOR_REMOTE_TASK_AUTH_TOKEN: replace-before-production
  DISTRIBUTED_SQL_WORKER_OBJECT_STORE_ACCESS_KEY: distributed-sql
  DISTRIBUTED_SQL_WORKER_OBJECT_STORE_SECRET_KEY: distributed-sql-secret
  DISTRIBUTED_SQL_WORKER_REMOTE_TASK_AUTH_TOKEN: replace-before-production
  MINIO_ROOT_USER: distributed-sql
  MINIO_ROOT_PASSWORD: distributed-sql-secret
